v0.0.8
zenon-network/znn_cli_dart pull request #9
Opened 2024-07-10 17:31 UTC by KingGorrin

This PR updates the `znn_ledger_dart` dependency to use the latest version from zenon-network and fixes the `dcli` build conflict when building against the latest Dart SDK by updating the `dcli` dependency to version `4.0.4`.

**Additional changes**
- Workflow specifies a `stable` sdk specifier
- Use latest major `dart-lang/setup-dart@v1` action
- Update sdk environment
- Pub upgrade
- Bump version to `0.0.8`

2024-07-11 09:00 UTC, vilkris4 requested changes
Please also update the CLI version number in `global.dart`.

2024-07-11 13:47 UTC, KingGorrin commented
> Please also update the CLI version number in `global.dart`.

Gotcha, always forget that one.

2024-07-11 20:40 UTC, KingGorrin commented
@vilkris4 did some tagging and applied them to all references

2024-07-12 10:48 UTC, vilkris4 approved these changes
LGTM

2024-07-12 12:28 UTC, 0x3639 approved these changes

2024-07-12 13:51 UTC, merged